# Generated by Django 5.2.12 on 2026-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="video_time",
            field=models.FloatField(default=0),
        ),
    ]
