# Generated by Django 5.2.12 on 2026-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_progress_video_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.URLField(default="https://via.placeholder.com/300"),
        ),
    ]
