# Generated by Django 5.2.12 on 2026-03-19 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_course_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="course",
            name="video_url",
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="users.course",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="users.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="progress",
            unique_together={("user", "lesson")},
        ),
    ]
