# Generated by Django 5.2.12 on 2026-03-19 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_lesson_options_remove_course_thumbnail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_lessons", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
