# Generated by Django 5.2.12 on 2026-03-19 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_lesson_allowed_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="course",
            name="users",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="allowed_users",
        ),
        migrations.AddField(
            model_name="lesson",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lesson"
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
