# Generated by Django 5.2.12 on 2026-04-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_lesson_video_url_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
